apiVersion: apps/v1
kind: Deployment
metadata:
  name: konomi-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konomi-api
  template:
    metadata:
      labels:
        app: konomi-api
    spec:
      containers:
        - name: konomi-api
          image: konomi-api:0.1.0-dev
          imagePullPolicy: IfNotPresent
          env:
            - name: KONOMI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: konomi-api-secret
                  key: KONOMI_API_KEY
            - name: KONOMI_VERSION
              value: "0.1.0-dev"
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
